name: Build, Test, and Deploy

on:
  push:
    branches:
      - main  # Adjust the branch if necessary
  pull_request:
    branches:
      - main  # Adjust for PRs targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Node.js (for example)
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Adjust to your Node.js version or other environment

      - name: Install dependencies
        run: npm install  # Adjust for your package manager or dependencies

      - name: Build the project
        run: npm run build  # Adjust based on your project

  test:
    runs-on: ubuntu-latest
    needs: build  # Ensures that the test job runs after the build job
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Node.js (if necessary for testing)
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test  # Adjust based on your test setup (e.g., Jest, Mocha)

  deploy:
    runs-on: ubuntu-latest
    needs: test  # Ensures deployment happens after tests pass
    if: success()  # Only runs if tests pass
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Node.js (if necessary for deployment)
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Deploy to production (example)
        run: npm run deploy  # Replace with your deploy command
        env:
          DEPLOYMENT_SECRET: ${{ secrets.DEPLOYMENT_SECRET }}  # Use GitHub Secrets to manage sensitive information
